@startuml
'https://plantuml.com/class-diagram

'Pakker, model og util
'Domænemodel giver nye entity klasser

package "util"
{
Class FileIo
FileIo :  - Scanner scanner
FileIo : + List <User> readUserData(String path)
FileIo : + void saveUserData(List <User> users)
FileIo : + String [] readLibraryData(String path, int length)

Class TextUI
TextUI : - Scanner scanner
TextUI : + String getInput(String msg)
TextUI : + void displayMessage(String msg)
}

package "model"
{
Interface Library
Library : + int getTitle()
Library : + int getRating()
Library : + int getReleaseDate()
Library : + String getGenre()

Library <|-- Movies
Library <|-- Series

Class Movies
Movies : - String title
Movies : - String genre
Movies : - int rating
Movies : - int releaseDate

Class Series
Series : - String title
Series : - String genre
Series : - int rating
Series : - int releaseDate

Class User
User : - String username
User : - String password
User : - List<Library> watchedLibrary
User : - List<Library> myLibrary
User : + void addToMyList(Library library)
User : + void removeFromMyList(Library library)
User : + void playMovie()
}

Class StreamingService
StreamingService : - FileIo io
StreamingService : - TextUI ui
StreamingService : - List<User> users
StreamingService : + startMenu()
StreamingService : + mainMenu()
StreamingService : + void Login()
StreamingService : + void Logout()
StreamingService : + void addUser(User user)
StreamingService : + void removeUser(User user)
StreamingService : + List<Library> searchLibrary(String search)

Class Main
Main : + static void main (String [] args)

Main *-- StreamingService
StreamingService *-- FileIo
StreamingService *-- User
StreamingService *-- TextUI
User *-- Library

@enduml